common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # django.contrib.auth 앱의 LoginView 클래스를 활용했으므로 별도의 views.py 파일 수정이 필요 없음
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    # / 페이지에 해당하는 urlpatterns
    path('', base_views.index, name='index'),
    path('admin/', admin.site.urls),
    # 사용자가 슬래시없이 주소를 입력해도 장고가 자동으로 슬래시를 붙여준다.
    # pybo/ 요청은 pybo/urls.py 참조
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views


# 네임스페이스 추가
app_name = 'pybo'

urlpatterns = [
    # url 별칭(name속성)으로 url 하드 코딩 문제 해결하기
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question, name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views/py
    path('vote/question/<int:question_id>', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>', vote_views.vote_answer, name='vote_answer'),


]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import Question


def index(request):
    """
    초기 화면
    """
    # 페이지 : 입력인자
    page = request.GET.get('page', '1')
    # 검색어
    kw = request.GET.get('kw', '')
    # 정렬기준
    so = request.GET.get('so', 'recent')

    if so == 'recommend':
        # annotate 함수는 Question 모델의 기존 필드에 num_voter 필드를 임시로 추가해 주는 함수
        # 그러면 filter or order_by 에서 num_voter 를 사용할 수 있게 됨
        question_list = Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        # 조회 : order_by(-붙으면 역순, 정렬할 속성)
        question_list = Question.objects.order_by('-create_date')

    if kw:
        # xx_icontains=(대소문자 가리지 않고 찾아줌)
        question_list = question_list.filter(
            Q(subject__icontains=kw) |                  # 제목 검색
            Q(content__icontains=kw) |                  # 내용 검색
            Q(author__username__icontains=kw) |         # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)   # 답변 글쓴이 검색
        ).distinct()

    # 페이징 처리 (10개씩 보여주기)
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    # render 함수는 context 데이터를 html 코드로 변환한다.
    return render(request, 'pybo/question_list.html', context)
    # return HttpResponse("안녕하세요. pybo에 오신것을 환영합니다.")


# url-mapping
def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    # get_object_or_404 함수는 모델의 기본키를 이용하여 모델 객체 한 건을 반환한다.
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 중복/반복되는 template include -->
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    <!-- 필드 오류를 출력한다. (입력값이 누락되었거나 형식에 맞지 않음) -->
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    <!-- Non 필드 오류를 출력한다. (입력값과 관계없이 발생한 오류) -->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">
                    {{ user.username }} (로그아웃)
                </a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>